# Generated by Django 5.0.4 on 2024-04-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofileimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
